services:
  hospitalDB:
    image: postgres:18.0-alpine
    container_name: hospitalDB
    environment:
      POSTGRES_HOST: ${HOST_DB}
      POSTGRES_PORT: ${PORT_DB}
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - postgres_data:/var/lib/postgis/data
    ports:
      - "5432:5432"
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB} -d ${NAME_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s 

volumes:
  postgres_data:
    driver: local

networks:
  hospital-network:
    driver: bridge
